### ISSUE TITLE
Improve timing of glip_upscale

### ISSUE THREAD

**Issue by imphil** [TUM-LIS/glip#32]
glip_upscale shows up in timing reports. We should probably delay the output for one cycle to get better timing.

@wallento sounds reasonable?

**Comment by imphil** [comment]
by "shows up in timing reports" I mean it's having a timing violation at 50 MHz :)

**Comment by wallento** [comment]
Its actually not upscale, I think. Its where you put it. There should be registers as near to it as possible.

Or is it the state of upscale (its very simple IIRC)?

**Comment by wallento** [comment]
But agree, the ingress path needs to be checked then.

**Comment by imphil** [comment]
I'll have a look. It seems our default demo designs use WIDTH == 8, so these modules aren't really used in testing.

**Comment by wallento** [comment]
Yeah, but then the MUX should hopefully be removed anyways. And that what it is a clog2(WIDTH)-Mux.
