### ISSUE TITLE
Up-/ downscaler problems at high frequencies

### ISSUE THREAD

**Issue by koenenwmn** [TUM-LIS/glip#37]
There is an issue when running the loopback test with the up-/ downscaler modules in the fx3 toplevel at high frequencies.
At up to 63MHz they work fine. When I try to run the demo at 80MHz and higher the loopback test reports a wrong value at byte 24577. It is always the same byte, no matter the frequency (80MHz and higher) or buffer size I use. More specifically, the 6114th 32 bit word the loopback test receives is all zeros.

**Comment by imphil** [comment]
Now solved with new FIFOs.
