### ISSUE TITLE
FX3: Write block size of 6 doesn't work in loopback demo

### ISSUE THREAD

**Issue by imphil** [TUM-LIS/glip#38]
The loopback demo has currently (since 34a595c5e27834b2c044a7845cb0fb8edd9d4ef7) a write block size of 8 set, as setting this to 6 as before doesn't result in working bus transactions.

Figure out what's going on here. Also make the block size a command line parameter, as 6 doesn't give any good speed on USB 3 (256 is a better choice here).

**Comment by imphil** [comment]
@koenenwmn this is fixed by now, isn't it?

**Comment by koenenwmn** [comment]
It is indeed fixed.
