### ISSUE TITLE
Create torture tests for unidirectional communication

### ISSUE THREAD

**Issue by imphil** [TUM-LIS/glip#44]
In order to reproduce https://github.com/optimsoc/optimsoc/issues/77 we want to have a test similar to loopback_measure which 
1. only sends data from the fpga to the host
2. inserts random waits between data to be sent
3. sends random, yet reproducible data (use LFSR with known seed for example)

If already 1 reproduces the data corruption we're seeing, that's fine. Otherwise we need to continue with 2 and 3.

**Comment by koenenwmn** [comment]
A stress test for unidirectional traffic both from host to FPGA and FPGA to host has been added in the stress_test branch. It is possible to add wait states on host as well as FPGA side. The issue can be reproduced using this test.
