### ISSUE TITLE
UART: High FPGA -> Host traffic causes data corruption

### ISSUE THREAD

**Issue by imphil** [TUM-LIS/glip#47]
See https://github.com/optimsoc/optimsoc/issues/75 for a full description.

We should try to reproduce this bug with GLIP only using  #44

**Comment by koenenwmn** [comment]
The bug can be reproduced with the vcu108 stress test demo when running:
   glip_io_stress_test -b uart -ospeed=3000000,device=/dev/ttyUSB0 -r -w 100

**Comment by imphil** [comment]
Fixed by 7dd4e10d1af5adc54543ca0a6e751925db1e3b62
